export const assets = {
    landsurface: "graphics/floor/grass.png",
    landroad: "graphics/floor/road.png",
    landdisplacement: "graphics/floor/horizon_map.png",
    cloud: "graphics/cloud.json",
    floorDecor: "graphics/floor/tallgrass.json",
    runman: "graphics/floor/running.json",
    pacesprite: "graphics/pace.json",
    outerpace: "graphics/progressbar.png",
    backgroundfront: "graphics/bg/backgroundfront.png",
    backgroundback: "graphics/bg/backgroundback.png",
    runprogress: "graphics/runprogress.png",
    fightman: "graphics/fightman.json",
    fightman2: "graphics/fightman2.json",
    armogus: "graphics/armogus.json",
    legolus: "graphics/legolus.json",
    absogus: "graphics/absogus.json",
};