export const assets = {
    landsurface: "graphics/floor/grass.png",
    landroad: "graphics/floor/road.png",
    landdisplacement: "graphics/floor/horizon_map.png",
    cloud: "graphics/cloud.json",
    floorDecor: "graphics/floor/tallgrass.json",
    runman: "graphics/floor/running.json",
    pacesprite: "graphics/pace.json",
    outerpace: "graphics/progressbar.png",
    backgroundfront: "graphics/bg/backgroundfront.png",
    backgroundback: "graphics/bg/backgroundback.png",
    runprogress: "graphics/runprogress.png",
    fightman: "graphics/fightman.json",
    fightman2: "graphics/fightman2.json",
    armogus: "graphics/armogus.json",
    legolus: "graphics/legolus.json",
    absogus: "graphics/absogus.json",
    enemyhealth: "graphics/enemyhealth.png",
    enemypack: "graphics/enemypack.png",
    factguy: "graphics/factguy.png",

    repsound: "audio/rep.wav",
    nextsound: "audio/dingbell.mp3",
    startsound: "audio/start.mp3",
    // connectedsound: "audio/atmospheric.mp3",

    gymmusic: "audio/ouroboros-by-kevin-macleod-from-filmmusic-io.mp3",
    runmusic: "audio/your-call-by-kevin-macleod-from-filmmusic-io.mp3",
};
